### ISSUE TITLE
a couple questions

### ISSUE THREAD

**Issue by uchagani** [bashah55/Shoe-Store#1]
How did you determine the priority of the user stories?  Was this given or did you make them up?

Why did u choose to write a manual test plan instead of automated tests?

**Comment by bashah55** [comment]
Hello, 

The prioritization of the user stories were assumed in the interest of being able to create thorough test cases based on some established assumptions since there are many possible variables and unknowns.
The instructions indicated to create test cases either manually or automated so I chose manual to demonstrate my manual test skills, but I am creating some automation tests.  I hope this answers your questions.

Thanks!
